on:
  port: 8080
  address: 0.0.0.0

admin:
  port: same
  address: 0.0.0.0

app:
  search: false
  navbar: true
  fluid: false
  cdn: auto
  contextPath: ''
  home: /
  menu: {}

main-zone: {}

admin-zone:
  home: /_
  brand: '<i class="fa fa-shield"></i> Rapidoid'
  search: false
  fluid: true
  menu:
    Overview: /_
    Routes: /_routes
    Configuration: /_config
    Deployment: /_deployment
    Processes: /_processes
    Metrics: /_metrics
    Application:
      Beans: /_beans
      Entities: /_entities
    Manage:
      Terminate / Restart: /_terminate
    Details:
      Classpath: /_classpath
      Memory pool: /_jmx/mempool
      JVM Threads: /_jmx/threads
      Operating system: /_jmx/os
      Garbage collection: /_jmx/gc
      Memory: /_jmx/memory
      Runtime: /_jmx/runtime
      Classes: /_jmx/classes
      Compilation: /_jmx/compilation

platform-zone:
  home: /_
  brand: '<i class="fa fa-shield"></i> Rapidoid'
  search: false
  fluid: true
  menu:
    Overview: /_
    Routes: /_routes
    Configuration: /_config
    Deployment: /_deployment
    Processes: /_processes
    Metrics: /_metrics
    Manage:
      Terminate / Restart: /_terminate
    Details:
      Classpath: /_classpath
      Memory pool: /_jmx/mempool
      JVM Threads: /_jmx/threads
      Operating system: /_jmx/os
      Garbage collection: /_jmx/gc
      Memory: /_jmx/memory
      Runtime: /_jmx/runtime
      Classes: /_jmx/classes
      Compilation: /_jmx/compilation

users:
  admin:
    roles: administrator

jobs:
  executor:
    threads: 256
  scheduler:
    threads: 64

hibernate:
  c3p0:
    debug: false
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 100
    acquireIncrement: 5
    maxStatementsPerConnection: 10
    idleConnectionTestPeriod: 300

c3p0:
  debug: false
  initialPoolSize: 5
  minPoolSize: 5
  maxPoolSize: 100
  acquireIncrement: 5
  maxStatementsPerConnection: 10
  idleConnectionTestPeriod: 300

oauth:
  google:
    scope: profile,email
    clientId: YOUR_GOOGLE_CLIENT_ID_HERE
    clientSecret: YOUR_GOOGLE_CLIENT_SECRET_HERE

  github:
    scope: user:email
    clientId: YOUR_GITHUB_CLIENT_ID_HERE
    clientSecret: YOUR_GITHUB_CLIENT_SECRET_HERE

  facebook:
    scope: public_profile,email
    clientId: YOUR_FACEBOOK_CLIENT_ID_HERE
    clientSecret: YOUR_FACEBOOK_CLIENT_SECRET_HERE

  linkedin:
    scope: r_basicprofile,r_emailaddress
    clientId: YOUR_LINKEDIN_CLIENT_ID_HERE
    clientSecret: YOUR_LINKEDIN_CLIENT_SECRET_HERE

net:
  address: 0.0.0.0
  port: 8080
# workers: ${cpus}
  bufSizeKB: 256
  noDelay: false
  syncBufs: true

http:
  timeout: 30000
  timeoutResolution: 5000
  maxPipeline: 10
  serverName: Rapidoid

  mandatoryHeaders:
    connection: true
    date: true
    server: true
    contentType: true

token:
  ttl: 0 # unlimited

log:
  level: info
  fancy: false # auto
